feat: add progress tacker logger to pregel context
neo4j/graph-data-science pull request #182
Opened 2022-04-12 06:29 UTC by frank-zsy

Signed-off-by: Frankzhaopku <syzhao1988@126.com>

Before submitting this PR, please make sure:
- [x] You signed the [Neo4j CLA](https://neo4j.com/developer/cla/#sign-cla) (Contributor License Agreement) so that we are allowed to ship your code in our library
- [ ] Your contribution is covered by tests

This PR tends to add a build-in logger to Pregel framework. close #180 

I looked into the code and `InitContext` and `ComputeContext` derive from `NodeCentricContext` which derives from `PregelContext`. And `MasterComputeContext` derives from `PregelContext`, so I add a private `ProgressTracker` reference into the `PregelContext` and expose three public functions `logDebug`, `logWarning` and `logMessage` which will call the same functions in the tracker, so developers can use them in all three contexts in the framework.

What I am not sure is:

- How to add or should I add test case to this PR?

2022-04-19 09:26 UTC, frank-zsy commented
@s1ck could you have a look on this pull please?

2022-04-19 09:35 UTC, s1ck commented
@frank-zsy Thanks for the PR. I was afk last week and didn't see it until now! Will have a look.

2022-04-19 14:40 UTC, s1ck requested changes
Looks good. Note, that the `ProgressTracker` always prefixes the message with the current phase the algo is in. This should be the iteration in case of Pregel.

I think we should also add a small paragraph to the docs (https://github.com/neo4j/graph-data-science/blob/master/doc/asciidoc/algorithms/algorithms-pregel-api.adoc). There are docs for all three contexts, but a specific section on `Logging` which explains that those methods are shared across all contexts would be nice.

2022-04-19 14:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/Pregel.java
> +        var context = new MasterComputeContext<>(config, graph, iteration, nodeValues, executor, this.progressTracker);
```suggestion
        var context = new MasterComputeContext<>(config, graph, iteration, nodeValues, executor, progressTracker);
```

2022-04-19 14:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
     * Log a debug message to the Neo4j log.
```

2022-04-19 14:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
     * Log a warning message to the Neo4j log.
```

2022-04-19 14:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
     * Log a info message to the Neo4j log.
```

2022-04-19 15:16 UTC, frank-zsy commented
Thanks, should I add the `Logging` section to `2.4` just before `Message reducer` or `2.6`?

2022-04-19 16:07 UTC, s1ck commented
> Thanks, should I add the `Logging` section to `2.4` just before `Message reducer` or `2.6`?

Let's do `2.6 Logging` and briefly describe that the "following methods" are available at the three context objects and that they allow us to inject custom messages into the progress log of the algorithm execution.

2022-04-20 08:40 UTC, s1ck requested changes
Thanks for the changes. It looks good, just some minor comments.

2022-04-20 08:40 UTC, s1ck commented on doc/asciidoc/algorithms/algorithms-pregel-api.adoc
> +The following functions are available in all three contexts(`InitContext`, `ComputeContext`, `MasterComputeContext`) to inject custom messages into the progress log of the algorithm execution.
```suggestion
The following methods are available for all contexts (`InitContext`, `ComputeContext`, `MasterComputeContext`) to inject custom messages into the progress log of the algorithm execution.
```

2022-04-20 08:40 UTC, s1ck commented on doc/asciidoc/algorithms/algorithms-pregel-api.adoc
> +// All contexts are derived from PregelContext class
```suggestion
// All contexts inherit from PregelContext
```

2022-04-20 08:40 UTC, s1ck commented on doc/asciidoc/algorithms/algorithms-pregel-api.adoc
> +NOTE: The log functions will always prefix the message with the current phase of current algorithm which is the iteration in case of Pregel.
```suggestion
```

2022-04-20 08:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
```

2022-04-20 08:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
```

2022-04-20 08:40 UTC, s1ck commented on pregel/src/main/java/org/neo4j/gds/beta/pregel/context/PregelContext.java
> +     * @param message
```suggestion
```

2022-04-20 10:24 UTC, frank-zsy commented
Thanks for the review, I looked into the documentation carefully and found almost equal number of `function` and `method`, is there any convention when to use which?

2022-04-21 07:34 UTC, s1ck commented
> Thanks for the review, I looked into the documentation carefully and found almost equal number of `function` and `method`, is there any convention when to use which?

It's true that it's mixed up, but since we use Java code snippets here, using `method` seems appropriate.

2022-04-21 07:45 UTC, s1ck approved these changes
Looks good. Thanks for the contribution.

Since the public repo is synced from our internal repo, I will close the PR, and apply your changes to the private repo. Once merged, it'll be visible within the next days. You can expect the change to part of the next 2.0 patch release.

2022-04-21 08:05 UTC, closed without merging

2022-04-21 08:55 UTC, frank-zsy commented
Sure, thanks.